<a href="https://colab.research.google.com/github/cmd0850/Chislovy_metodi/blob/main/%D0%9B%D0%A04_%D0%94%D0%96%D0%95%D0%9D%D0%A7%D0%90%D0%9A%D0%9E_10_%D0%B2%D0%B0%D1%80%D1%96%D0%B0%D0%BD%D1%82.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

In [ ]:
import numpy as np
numpy_version = np.__version__
numpy_version

'2.0.2'

In [ ]:
matrix=np.random.randint(1, 6, size=(3,3))

matrix

array([[1, 3, 4],
       [3, 4, 1],
       [3, 4, 3]])

In [ ]:
det=np.linalg.det(matrix)
det

np.float64(-10.000000000000002)

In [ ]:
product=np.prod(matrix)
product

np.int64(5184)

In [ ]:
prod_1=np.prod(matrix[0])
prod_2=np.prod(matrix[1])
prod_3=np.prod(matrix[2])
prod_1*prod_2*prod_3

np.int64(5184)

In [ ]:
sum_1=np.sum(matrix)
sum_1

np.int64(26)

In [ ]:
np.max(matrix)

np.int64(4)

In [ ]:
np.min(matrix)

np.int64(1)

In [ ]:
np.mean(matrix)

np.float64(2.888888888888889)

In [ ]:
np.sqrt(matrix)

array([[1.        , 1.73205081, 2.        ],
       [1.73205081, 2.        , 1.        ],
       [1.73205081, 2.        , 1.73205081]])

In [ ]:
np.sum(matrix, axis=1).reshape(-1, 1)

array([[ 8],
       [ 8],
       [10]])

In [ ]:
vector=np.random.randint(0, 10, size=25)
vector

array([9, 1, 6, 4, 2, 7, 5, 8, 8, 8, 4, 6, 6, 5, 6, 7, 7, 4, 7, 9, 5, 0,
       4, 1, 2])

In [ ]:
sort_vector=np.sort(vector)[::-1]
sort_vector

array([9, 9, 8, 8, 8, 7, 7, 7, 7, 6, 6, 6, 6, 5, 5, 5, 4, 4, 4, 4, 2, 2,
       1, 1, 0])

In [30]:
a = np.array([[3, 2, 1], [2, -1, 1], [1, 5, 0]])
b = np.array([5, 6, -3])

x = np.linalg.solve(a, b)
print('Вбудована функція', x)

inv_a = np.linalg.inv(a)
x1 = inv_a.dot(b)
print('Матричний метод', x1)

Вбудована функція [ 2. -1.  1.]
Матричний метод [ 2. -1.  1.]


In [31]:
def kramer(a, b):
    det_a = np.linalg.det(a)
    if det_a != 0:
        solutions = []
        for i in range(len(a)):
            modified_a = np.copy(a)
            modified_a[:, i] = b
            solutions.append(round(np.linalg.det(modified_a) / det_a, 1))

        print('Solving a system of linear algebraic equations by Cramer\'s method:')


    else:
        print('Determinant equals zero, the system has no solutions')
    return solutions
print(kramer(a, b))


Solving a system of linear algebraic equations by Cramer's method:
[np.float64(2.0), np.float64(-1.0), np.float64(1.0)]
